### ISSUE TITLE
Switch default filename extension from .b9 to .b9.hs

### ISSUE THREAD

**Issue by rusio** [sheyll/b9-vm-image-builder#2]
Rationale: while .b9 denotes file association with the b9 tool, .hs denotes association with the Haskell language (which is used in .b9 files) and provides an automatic hint to the editor and to the Haskell compiler. Combining the two extensions gives us the best of both - application-specific semantics (.b9) and Haskell-specific syntax (.hs).

**Comment by sheyll** [comment]
B9 does not impose restrictions on the file extension. Note that the haskell compiler is not involved in reading a b9 file.
