### ISSUE TITLE
Build failure with ghc 8.4

### ISSUE THREAD

**Issue by DanBurton** [sheyll/b9-vm-image-builder#4]
```
Building library for b9-0.5.35..

[ 2 of 27] Compiling B9.B9Config      ( src/lib/B9/B9Config.hs, dist/build/B9/B9Config.o )

src/lib/B9/B9Config.hs:54:10: error:
    • No instance for (Semigroup B9Config)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid B9Config’
   |
54 | instance Monoid B9Config where
   |          ^^^^^^^^^^^^^^^

src/lib/B9/B9Config.hs:142:19: error:
    • Could not deduce (Semigroup B9Config) arising from a use of ‘<>’
      from the context: MonadIO m
        bound by the type signature for:
                   writeInitialB9Config :: forall (m :: * -> *).
                                           MonadIO m =>
                                           Maybe SystemPath -> B9Config -> ConfigParser -> m ()
        at src/lib/B9/B9Config.hs:(126,1)-(130,31)
    • In the expression: defaultB9Config <> cliCfg
      In an equation for ‘c’: c = defaultB9Config <> cliCfg
      In the expression:
        do let cp = emptyCP
               c = defaultB9Config <> cliCfg
           cp1 <- add_section cp cfgFileSection
           cp2 <- setshow cp1 cfgFileSection verbosityK (verbosity c)
           cp3 <- setshow cp2 cfgFileSection logFileK (logFile c)
           ....
    |
142 |               c = defaultB9Config <> cliCfg
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sheyll** [comment]
Thank you, could you help me reproduce this, I do not get this error.

**Comment by sheyll** [comment]
Thanks for the report, I will look into it as soon as stack nightly works on my machine.

There is a [bug report](https://github.com/commercialhaskell/stack/pull/3916) for this. 


It fails with:

    $ stack  --resolver nightly-2018-03-13 build  --ghc-options -Werror
    Downloaded nightly-2018-03-13 build plan.
    The following packages specified by flags or options are not found: persistent-sqlite yaml

How do you build b9?

**Comment by DanBurton** [comment]
On the stackage build server, we basically use a scripted series of `runghc Setup.hs`, which is not very ergonomic for humans to reproduce.

Locally, I use `stack upgrade --git --git-branch stable` to pull in the bugfix. I've also heard they are working on a stack minor release, so once that happens you could just `stack upgrade`.

**Comment by DanBurton** [comment]
n.b. `stack upgrade --git` is no longer needed, if you use `nightly-2018-03-16` or later.

**Comment by sheyll** [comment]
ah ... thanks :)
